apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.identity/client-id: eded7089-563e-478d-bb95-bc7324cac906
  labels:
    azure.workload.identity/use: "true"