apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: trading-serviceaccount
      containers:
      - name: trading
        image: playeconomyaxsg1.azurecr.io/play.trading:1.0.5
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: playeconomyaxsg1
          - name: ServiceSettings__Authority
            value: https://playeconomyaxsg1.eastus.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5006
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5006
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5006
          initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
  - port: 80
    targetPort: 5006

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-serviceaccount
  annotations:
    azure.workload.identity/client-id: eded7089-563e-478d-bb95-bc7324cac906
  labels:
    azure.workload.identity/use: "true"